sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

# 配置文件的根节点
oss:
  # OSS的端点
  endpoint: "https://oss-cn-beijing.aliyuncs.com"
  # 凭证提供者配置
  credentialsProviderType: "environmentVariable"
  # 存储桶名称
  bucketName: "zpxweb-talis"